[project]
name = "decentralized-crowdfunding"
description = "A decentralized crowdfunding platform"
authors = []
telemetry = false
cache_dir = "./.cache"

[contracts.crowdfunding]
path = "contracts/crowdfunding.clar"
clarity_version = 2
epoch = 2.1

[repl]
costs_version = 2
parser_version = 2
